apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "microservice.fullname" . }}
  labels:
    {{- include "microservice.labels" . | nindent 4 }}
  annotations:
    repository: "https://bitbucket.org/solaireresortcasino/{{ include "microservice.fullname" . }}"
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "microservice.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "microservice.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        - name: {{ include "microservice.fullname" . }}-key
          secret:
            secretName: {{ include "microservice.fullname" . }}-key
      imagePullSecrets:
        - name: {{ include "microservice.fullname" . }}-ips
      serviceAccountName: {{ include "microservice.fullname" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          volumeMounts:
            - name: {{ include "microservice.fullname" . }}-key
              mountPath: /var/secrets/google
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /var/secrets/google/key.json
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  key: NODE_ENV
                  name: {{ include "microservice.fullname" . }}
            - name: SENSEN_TOPIC
              valueFrom:
                configMapKeyRef:
                  key: SENSEN_TOPIC
                  name: {{ include "microservice.fullname" . }}
            - name: SENSEN_CONSUMER_USERNAME
              valueFrom:
                secretKeyRef:
                  key:  SENSEN_CONSUMER_USERNAME
                  name: {{ include "microservice.fullname" . }}
            - name: SENSEN_CONSUMER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key:  SENSEN_CONSUMER_PASSWORD
                  name: {{ include "microservice.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
